set serveroutput on size 100000
set echo off
set verify off
set termout on
set feedback off
set newpage none
set pages 0
set heading off
set linesize 750
set term off;

drop table LMS_OVERVIEW;

create table LMS_OVERVIEW (
        "GROUPP" CHAR(1 BYTE), 
	"AGGREGATION_LEVEL" CHAR(1 BYTE), 
	"ORACLE_CSI" CHAR(1 BYTE), 
	"ORACLE_PRODUCT_CATEGORY" CHAR(9 BYTE), 
	"PHYSICAL_MACHINE_ID" VARCHAR2(256 BYTE), 
	"VIRTUAL_MACHINE_ID" VARCHAR2(256 BYTE), 
	"DATABASE_EDITION" VARCHAR2(256 BYTE), 
	"DATABASE_NAME" VARCHAR2(256 BYTE), 
	"DATABASE_VERSION" VARCHAR2(256 BYTE), 
	"OPTIONS_INSTALLED" VARCHAR2(1024 BYTE), 
	"OPTIONS_IN_USE" VARCHAR2(1024 BYTE), 
	"PACKS_GRANTED" VARCHAR2(1024 BYTE), 
	"PACKS_AGREED" VARCHAR2(1024 BYTE), 
	"APPLICATION_NAME" CHAR(1 BYTE), 
	"APPLICATION_STATUS" CHAR(1 BYTE), 
	"USER_COUNT_DB" NUMBER, 
	"USER_COUNT_APP" CHAR(1 BYTE), 
	"SERVER_MANUFACTURER" VARCHAR2(256 BYTE), 
	"SERVER_MODEL" VARCHAR2(512 BYTE), 
	"OPERATINGSYSTEM_TYPE_PRE" VARCHAR2(255 BYTE), 
	"OPERATING_SYSTEM" NUMBER, 
	"SOCKETS_POPULATED_PHYSICAL" NUMBER, 
	"TOTAL_PHYSICAL_CORES" NUMBER, 
	"PROCESSOR_IDENTIFIER" VARCHAR2(256 BYTE), 
	"PROCESSOR_SPEED" VARCHAR2(44 BYTE), 
	"SOCKET_CAPACITY_PHYSICAL" CHAR(1 BYTE), 
	"TOTAL_LOGICAL_CORES" NUMBER, 
	"PARTITIONING_METHODS" CHAR(100 BYTE), 
	"DATABASE_ROLE" VARCHAR2(255 BYTE), 
	"SERVER_NAME_IN_THE_CLUSTER" CHAR(1 BYTE), 
	"TOP_CONCURRENCY_TIMESTAMP" CHAR(1 BYTE), 
	"SESSIONS" CHAR(1 BYTE), 
	"INSTANCE_SESSIONS_HIGHWATER" NUMBER, 
	"INSTALL_DATE" VARCHAR2(255 BYTE), 
	"MEASUREMENT_COMMENT" CHAR(1 BYTE)
);


declare

v_str varchar2(32766);
v_table_name varchar2(100);
stmt varchar2(350);
v_1 varchar2(50);
v_2 varchar2(50);

begin
v_1 := &2;
if (v_1 = 'x') then
    v_2 := '';
else
    v_2 := v_1;
end if;

stmt :=  'select report_name from ' || concat(v_2, 'report_store') || ' where query_name = ''oracle_LMS_overview_pres''';
execute immediate stmt into v_table_name;
dbms_output.put_line(v_table_name);

v_str:='INSERT INTO LMS_OVERVIEW
(
"GROUPP",
AGGREGATION_LEVEL ,
ORACLE_CSI,
ORACLE_PRODUCT_CATEGORY   ,
PHYSICAL_MACHINE_ID       ,
VIRTUAL_MACHINE_ID        ,
DATABASE_EDITION          ,
DATABASE_NAME             ,
DATABASE_VERSION          ,
OPTIONS_INSTALLED         ,
OPTIONS_IN_USE            ,
PACKS_GRANTED             ,
PACKS_AGREED              ,
APPLICATION_NAME          ,
APPLICATION_STATUS        ,
USER_COUNT_DB             ,
USER_COUNT_APP            ,
SERVER_MANUFACTURER       ,
SERVER_MODEL              ,
OPERATINGSYSTEM_TYPE_PRE  ,
OPERATING_SYSTEM          ,
SOCKETS_POPULATED_PHYSICAL,
TOTAL_PHYSICAL_CORES      ,
PROCESSOR_IDENTIFIER      ,
PROCESSOR_SPEED           ,
SOCKET_CAPACITY_PHYSICAL  ,
TOTAL_LOGICAL_CORES       ,
PARTITIONING_METHODS      ,
DATABASE_ROLE             ,
SERVER_NAME_IN_THE_CLUSTER,
TOP_CONCURRENCY_TIMESTAMP ,
SESSIONS                  ,
INSTANCE_SESSIONS_HIGHWATER ,
INSTALL_DATE              ,
MEASUREMENT_COMMENT
)
SELECT 
"GROUPP",
AGGREGATION_LEVEL ,
ORACLE_CSI,
ORACLE_PRODUCT_CATEGORY   ,
PHYSICAL_MACHINE_ID       ,
VIRTUAL_MACHINE_ID        ,
DATABASE_EDITION          ,
DATABASE_NAME             ,
DATABASE_VERSION          ,
OPTIONS_INSTALLED         ,
OPTIONS_IN_USE            ,
PACKS_GRANTED             ,
PACKS_AGREED              ,
APPLICATION_NAME          ,
APPLICATION_STATUS        ,
USER_COUNT_DB             ,
USER_COUNT_APP            ,
SERVER_MANUFACTURER       ,
SERVER_MODEL              ,
OPERATINGSYSTEM_TYPE_PRE  ,
OPERATING_SYSTEM          ,
SOCKETS_POPULATED_PHYSICAL,
TOTAL_PHYSICAL_CORES      ,
PROCESSOR_IDENTIFIER      ,
PROCESSOR_SPEED           ,
SOCKET_CAPACITY_PHYSICAL  ,
TOTAL_LOGICAL_CORES       ,
PARTITIONING_METHODS      ,
DATABASE_ROLE             ,
SERVER_NAME_IN_THE_CLUSTER,
TOP_CONCURRENCY_TIMESTAMP ,
SESSIONS                  ,
INSTANCE_SESSIONS_HIGHWATER ,
INSTALL_DATE              ,
MEASUREMENT_COMMENT       
FROM '||v_table_name;


EXECUTE IMMEDIATE v_str;

exception
when others then
  dbms_output.put_line(sqlerrm);
  raise;
end;
/

spool &1

select '"GROUPP","AGGREGATION_LEVEL","ORACLE_CSI","ORACLE_PRODUCT_CATEGORY","PHYSICAL_MACHINE_ID","VIRTUAL_MACHINE_ID","DATABASE_EDITION","DATABASE_NAME","DATABASE_VERSION","OPTIONS_INSTALLED","OPTIONS_IN_USE","PACKS_GRANTED","PACKS_AGREED","APPLICATION_NAME","APPLICATION_STATUS","USER_COUNT_DB","USER_COUNT_APP","SERVER_MANUFACTURER","SERVER_MODEL","OPERATINGSYSTEM_TYPE_PRE","OPERATING_SYSTEM","SOCKETS_POPULATED_PHYSICAL","TOTAL_PHYSICAL_CORES","PROCESSOR_IDENTIFIER","PROCESSOR_SPEED","SOCKET_CAPACITY_PHYSICAL","TOTAL_LOGICAL_CORES","PARTITIONING_METHODS","DATABASE_ROLE","SERVER_NAME_IN_THE_CLUSTER","TOP_CONCURRENCY_TIMESTAMP","SESSIONS","INSTANCE_SESSIONS_HIGHWATER","INSTALL_DATE","MEASUREMENT_COMMENT"' from dual;

SELECT '"'||NVL(TRIM("GROUPP"),'NULL')||'","'||NVL(TRIM(AGGREGATION_LEVEL),'NULL')||'","'
||NVL(TRIM(ORACLE_CSI),'NULL')||'","'||NVL(TRIM(ORACLE_PRODUCT_CATEGORY),'NULL')||'","'
||NVL(TRIM(PHYSICAL_MACHINE_ID),'NULL')||'","'||NVL(TRIM(VIRTUAL_MACHINE_ID),'NULL')||'","'
||NVL(TRIM(DATABASE_EDITION),'NULL')||'","'||NVL(TRIM(DATABASE_NAME),'NULL')||'","'
||NVL(TRIM(DATABASE_VERSION),'NULL')||'","'||NVL(TRIM(OPTIONS_INSTALLED),'NULL')||'","'
||NVL(TRIM(OPTIONS_IN_USE),'NULL')||'","'||NVL(TRIM(PACKS_GRANTED),'NULL')||'","'
||NVL(TRIM(PACKS_AGREED),'NULL')||'","'||NVL(TRIM(APPLICATION_NAME),'NULL')||'","'
||NVL(TRIM(APPLICATION_STATUS),'NULL')||'","'||NVL(TRIM(USER_COUNT_DB),'NULL')||'","'
||NVL(TRIM(USER_COUNT_APP),'NULL')||'","'||NVL(TRIM(SERVER_MANUFACTURER),'NULL')||'","'
||NVL(TRIM(SERVER_MODEL),'NULL')||'","'||NVL(TRIM(OPERATINGSYSTEM_TYPE_PRE),'NULL')||'","'
||NVL(TRIM(OPERATING_SYSTEM),'NULL')||'","'||NVL(TRIM(SOCKETS_POPULATED_PHYSICAL),'NULL')||'","'
||NVL(TRIM(TOTAL_PHYSICAL_CORES),'NULL')||'","'||NVL(TRIM(PROCESSOR_IDENTIFIER),'NULL')||'","'
||NVL(TRIM(PROCESSOR_SPEED),'NULL')||'","'||NVL(TRIM(SOCKET_CAPACITY_PHYSICAL),'NULL')||'","'
||NVL(TRIM(TOTAL_LOGICAL_CORES),'NULL')||'","'||NVL(TRIM(PARTITIONING_METHODS),'NULL')||'","'
||NVL(TRIM(DATABASE_ROLE),'NULL')||'","'||NVL(TRIM(SERVER_NAME_IN_THE_CLUSTER),'NULL')||'","'
||NVL(TRIM(TOP_CONCURRENCY_TIMESTAMP),'NULL')||'","'||NVL(TRIM(SESSIONS),'NULL')||'","'
||NVL(TRIM(INSTANCE_SESSIONS_HIGHWATER),'NULL')||'","'||NVL(TRIM(INSTALL_DATE),'NULL')||'","'
||NVL(TRIM(MEASUREMENT_COMMENT),'NULL')||'"'
FROM LMS_OVERVIEW;

spool off

quit;


