#!/usr/bin/expect -f
set installHome "/home/bdna/install770"
set cantonPath "/home/bdna/automation/us_canton"
set timeout -1

spawn sudo ssh -D 22 bdna@192.168.8.245
expect {
       "(yes/no)?" {send "yes\r";exp_continue}
       "*password:" {send "bdna\r" }
}

expect "\\$"
send "sh $installHome/bin/runjava.sh com.bdna.pl.util.BulkLoader -i:4 -f:$cantonPath/01_network.txt\r"
expect "\\$"
send "sh $installHome/bin/runjava.sh com.bdna.pl.util.BulkLoader -i:5 -f:$cantonPath/02_exclusions.txt\r"
expect "\\$"
send "sh $installHome/bin/runjava.sh com.bdna.pl.util.BulkLoader -i:3 -f:$cantonPath/05_groups.txt\r"
expect "\\$"
send "sh $installHome/bin/runjava.sh com.bdna.agenda.BulkCommon BulkCred4 $cantonPath/06_credentials.txt\r"
expect "\\$"
send "sh $installHome/bin/runjava.sh com.bdna.agenda.BulkCommon BulkTask4 $cantonPath/07_task_all.txt\r"
expect "]\\$"
send "exit\r"
interact

