#!/usr/bin/perl
use warnings;

#$sql0 = "(select MIN(CAT_CREATE_DATE) FROM (SELECT COALESCE(CAT_HW_MODEL_FDA.CREATE_DATE, CONVERT(DATETIME, '20000101', 120)) AS CAT_CREATE_DATE union all SELECT COALESCE(CAT_FDA.CREATE_DATE, CONVERT(DATETIME, '20000101', 120)) AS CAT_CREATE_DATE ) CAT_CREATE_DATE) as CAT_CREATE_DATE,";
#$ora0 = "LEAST(COALESCE(CAT_HW_MODEL_FDA.CREATE_DATE, CONVERT(DATETIME, '20000101', 120)),COALESCE(CAT_FDA.CREATE_DATE, CONVERT(DATETIME, '20000101', 120))) AS CAT_CREATE_DATE,";

#$sql1 = "(select Max(CAT_LAST_MODIFIED_DATE) FROM (SELECT COALESCE(CAT_HW_MODEL_FDA.LAST_MODIFIED_DATE, CONVERT(DATETIME, '20000101', 120)) AS CAT_LAST_MODIFIED_DATE union all SELECT COALESCE(CAT_FDA.LAST_MODIFIED_DATE, CONVERT(DATETIME, '20000101', 120)) AS CAT_LAST_MODIFIED_DATE ) CAT_LAST_MODIFIED_DATE) as CAT_LAST_MODIFIED_DATE";
#$ora1 = "GREATEST(COALESCE(CAT_HW_MODEL_FDA.LAST_MODIFIED_DATE, CONVERT(DATETIME, '20000101', 120)),COALESCE(CAT_FDA.LAST_MODIFIED_DATE, CONVERT(DATETIME, '20000101', 120))) AS CAT_LAST_MODIFIED_DATE,";

while(<STDIN>) {
if ($_=~m/(greatest|least).+?AS\s+([\_\w]+)/gi){
$funKey = $1;
$colName = $2;
}
$funKey = uc($funKey);

%funH=('LEAST','MIN','GREATEST','MAX');

$oraLine = $_;
while($oraLine=~m/(COALESCE.+?\)\))/gi)
{
 push @colList,$1;
}

$sqlLine = join (" AS CAT_LAST_MODIFIED_DATE union all SELECT ",@colList);

$end = "AS $colName \) $colName AS $colName";
print "Trans ORA to SQL:\n";
printf "\(select $funH{$funKey}\($colName\) FROM \(SELECT $sqlLine $end\n";

}
